"""Init DB

Revision ID: 74c5c8d4b8a4
Revises:
Create Date: 2025-06-22 00:04:05.636673

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import chatbot.models


# revision identifiers, used by Alembic.
revision: str = "74c5c8d4b8a4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("owner", sa.Text(), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("created_at", chatbot.models.TZDateTime(), nullable=False),
        sa.Column("last_message_at", chatbot.models.TZDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_owner"), "conversation", ["owner"], unique=False
    )
    op.create_index(
        "ix_conversation_owner_pinned_last_message_at_id",
        "conversation",
        ["owner", "pinned", "last_message_at", "id"],
        unique=False,
    )
    op.create_table(
        "share",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("owner", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("snapshot_ref", sa.JSON(), nullable=False),
        sa.Column("created_at", chatbot.models.TZDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_share_owner"), "share", ["owner"], unique=False)
    op.create_index(
        "ix_share_owner_created_at_id",
        "share",
        ["owner", "created_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_share_owner_created_at_id", table_name="share")
    op.drop_index(op.f("ix_share_owner"), table_name="share")
    op.drop_table("share")
    op.drop_index(
        "ix_conversation_owner_pinned_last_message_at_id", table_name="conversation"
    )
    op.drop_index(op.f("ix_conversation_owner"), table_name="conversation")
    op.drop_table("conversation")
    # ### end Alembic commands ###
