injectRequestHeaders:
  - name: X-Forwarded-Groups
    values:
      - claim: groups
  - name: X-Forwarded-User
    values:
      - claim: user
  - name: X-Forwarded-Email
    values:
      - claim: email
  - name: X-Forwarded-Preferred-Username
    values:
      - claim: preferred_username
injectResponseHeaders:
  - name: X-Forwarded-Groups
    values:
      - claim: groups
  - name: X-Forwarded-User
    values:
      - claim: user
  - name: X-Forwarded-Email
    values:
      - claim: email
  - name: X-Forwarded-Preferred-Username
    values:
      - claim: preferred_username
metricsServer:
  BindAddress: ""
  SecureBindAddress: ""
  TLS: null
providers:
  # only the first provider works now.
  # see <https://github.com/oauth2-proxy/oauth2-proxy/issues/926>
  - provider: gitlab
    id: gitlab
    name: gitlab
    clientID: e8bf4b6f0846fa048e68540cdaceafd340cd99a915147c77f0cbc8f4f264cbc1
    clientSecret: gloas-b455bf581f73358cd537eee286416fb495f61ed19809a6d16d2e51ee5c1d65ef
    oidcConfig:
      issuerUrl: https://gitlab.com
      audienceClaims:
        - aud
  # gitee not working
  - provider: github
    id: gitee
    name: gitee
    clientID: c9f90f7eea23453da556bf86924c3f468bc1b40740a533d6e3bee837a6ac7739
    clientSecret: 0872160c0c38ce659554d2d6bd10dca0022a57b6b4792594c45c65380d9184e5
    loginUrl: https://gitee.com/oauth/authorize
    redeemUrl: https://gitee.com/oauth/access_token
    scope: user_info emails
    # validateUrl: https://gitee.com/edwardlol/api/v1
  - provider: github
    id: github
    name: github
    clientID: 13cf570549ff0674230c
    clientSecret: 4b7409c02ebaab91a96152d2ac5cc2cc31c4292b
  - provider: google
    id: google
    name: google
    clientID: 210937179771-sfbnkrnfa5osl6fdrelrk6um4qr11dii.apps.googleusercontent.com
    clientSecret: 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
    googleConfig: {}
    loginURLParameters:
      - default:
          - force
        name: approval_prompt
server:
  BindAddress: 0.0.0.0:4180
  SecureBindAddress: ""
  TLS: null
# upstreamConfig is required or we will get 404 error.
upstreamConfig:
  upstreams:
  - id: static://200
    path: /
    static: true
    staticCode: 200
