apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: chatbot-ext-authz
spec:
  action: CUSTOM
  provider:
    name: chatbot-oauth2-proxy
  rules:
    - to:
        - operation:
            notPaths:
              - /metrics
              - /share/{*}
              - /api/shares/{*}
              - /static/{*}
              - /favicon.ico
              - /assets/{*}
              - /vite.svg
              - /manifest.json
        - operation:
            paths:
              - /api/shares/{*}
            notMethods:
              - GET
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: default-allow-all
spec:
  action: ALLOW
  rules:
    - {}
