apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: edwardlol/chatbot:latest
          args:
            - --host
            - "0.0.0.0"
            - --port
            - "8000"
          envFrom:
            - configMapRef:
                name: chatbot
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "1"
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 1Gi
