apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chat

labels:
  - pairs:
      app: chatbot
      owner: edwardzjl  # this will expose chatbot by knative public domain
    includeSelectors: false

resources:
  - ../third-party/redis
  - ksvc.yaml

configMapGenerator:
  - name: chatbot
    envs:
      - params.env

# currently knative does not recognize configmaps with suffix hash
generatorOptions:
  disableNameSuffixHash: true

images:
  - name: edwardlol/chatbot
    newTag: v0.1.10
