apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app: chatbot
      app.kubernetes.io/name: chatbot
      app.kubernetes.io/version: "994e859"
      app.kubernetes.io/managed-by: kubectl
    includeSelectors: false

resources:
  - deployment.yaml
  - service.yaml
  - service-monitor.yaml
  - autoscaler.yaml

configMapGenerator:
  - name: chatbot
    envs:
      - params.env

secretGenerator:
  - name: chatbot
    envs:
      - secret-params.env

# currently knative does not recognize configmaps with suffix hash
generatorOptions:
  disableNameSuffixHash: true

images:
  - name: edwardlol/chatbot
    newTag: "994e859"
