apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app: chatbot
      app.kubernetes.io/name: chatbot
      app.kubernetes.io/version: 0.6.3
      app.kubernetes.io/managed-by: kubectl
    includeSelectors: false

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: chatbot
    envs:
      - params.env

# currently knative does not recognize configmaps with suffix hash
generatorOptions:
  disableNameSuffixHash: true

images:
  - name: edwardlol/chatbot
    newTag: 0.6.4
