# Websockets do not work with Knative Service's domainmapings by default
# See <https://github.com/knative/serving/issues/7933#issuecomment-786139169>
# and <https://github.com/knative/serving/issues/13083#issuecomment-1318301501>

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - virtual-service.yaml
  - authorizationpolicy.yaml

components:
  - ../../components/pgbouncer
  - ../../components/monitoring
  - ../../components/auth
  # I need to tweak the scaling metrics
  # - ../../components/autoscaler
