# Websockets do not work with Knative Service's domainmapings by default
# See <https://github.com/knative/serving/issues/7933#issuecomment-786139169>
# and <https://github.com/knative/serving/issues/13083#issuecomment-1318301501>

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jlzhou-chatbot

resources:
  - ../../base
  - virtual-service.yaml
