apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chatbot
spec:
  template:
    spec:
      containers:
        - image: edwardlol/chatbot:latest
          args:
            - --host
            - "0.0.0.0"
            - --port
            - "8080"
          envFrom:
            - configMapRef:
                name: chatbot
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "1"
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 1Gi
