apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - deployment.yaml
  - service.yaml

components:
  - components/redis

configMapGenerator:
  - name: oauth2-proxy
    files:
      - oauth2-proxy.yaml

secretGenerator:
  - name: oauth2-proxy
    envs:
      - secret-params.env

# we will mount configmaps so we can't use suffix hash
generatorOptions:
  disableNameSuffixHash: true

images:
  - name: quay.io/oauth2-proxy/oauth2-proxy
    newTag: v7.8.0
