injectResponseHeaders:
  - name: X-Forwarded-Groups
    values:
      - claim: groups
  - name: X-Forwarded-User
    values:
      - claim: user
  - name: X-Forwarded-Email
    values:
      - claim: email
  - name: X-Forwarded-Preferred-Username
    values:
      - claim: preferred_username
metricsServer:
  BindAddress: ""
  SecureBindAddress: ""
  TLS: null
providers:
  # only the first provider works now.
  # see <https://github.com/oauth2-proxy/oauth2-proxy/issues/926>
  - provider: google
    id: google
    name: google
    clientID: ${PROVIDERS_GOOGLE_CLIENTID}
    clientSecret: ${PROVIDERS_GOOGLE_CLIENTSECRET}
    googleConfig: {}
    loginURLParameters:
      - default:
          - force
        name: approval_prompt
server:
  BindAddress: 0.0.0.0:4180
  SecureBindAddress: ""
  TLS: null
# upstreamConfig is required or we will get 404 error.
upstreamConfig:
  upstreams:
  - id: static://200
    path: /
    static: true
    staticCode: 200
