apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
              name: service-port
              protocol: TCP
          volumeMounts:
            - name: redis-data
              mountPath: /data
              readOnly: false
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
