# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: redis
    newTag: 7.4.2-alpine
