apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - name: tcp
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app.kubernetes.io/name: redis
  type: ClusterIP
