# forward ports in devcontainer.json
version: '3'
services:
  chatbot:
    image: mcr.microsoft.com/devcontainers/python:3.11
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - redis

  redis:
    image: redis/redis-stack:7.2.0-v6
