apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: chatbot
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: chatbot
  endpoints:
    - port: http
      path: /metrics
