apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: chatbot-ext-authz
spec:
  selector:
    matchLabels:
      app: chatbot
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: default-allow-all
spec:
  selector:
    matchLabels:
      app: chatbot
