apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jlzhou-chatbot

resources:
  - namespace.yaml
  - ../../base
  - authorizationpolicy.yaml

components:
  - ../../components/pgbouncer
  - ../../components/monitoring
  - ../../components/ingress/gateway-api
  - ../../components/ext-authz/provider/oauth2-proxy
  # I need to tweak the scaling metrics
  # - ../../components/autoscaler
