from prometheus_client import Counter

input_tokens = Counter(
    "input_tokens", "Number of input tokens to the LLM", ["user_id", "model_name"]
)
output_tokens = Counter(
    "output_tokens",
    "Number of tokens generated by the LLM",
    ["user_id", "model_name"],
)
