apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgbouncer
  name: pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: session-ctn
          image: bitnami/pgbouncer:latest
          envFrom:
            - configMapRef:
                name: pgbouncer-bitnami
            - secretRef:
                name: pgbouncer-bitnami
          ports:
            - containerPort: 5432
              name: session-prt
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
          volumeMounts:
            - name: config-vol
              mountPath: /bitnami/pgbouncer/conf/
              readOnly: true
      volumes:
        - name: config-vol  # cannot name it to 'config' or kubernetes will not be able to find it.
          projected:
            sources:
              - configMap:
                  name: pgbouncer
              - secret:
                  name: pgbouncer
                  items:
                    - key: auth_file
                      path: userlist.txt
      # assign pods to nodes with the postgres primary
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - postgres
                    - key: replicationRole
                      operator: In
                      values:
                        - primary
                topologyKey: kubernetes.io/hostname
              weight: 100
      tolerations:
        - effect: NoSchedule
          key: usage
          operator: Equal
          value: rdbms
