apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: pgbouncer
    files:
      - pgbouncer.ini
  # The bitnami pgbouncer image requires some environment variables to work, although they are overridden by the config file
  - name: pgbouncer-bitnami
    envs:
      - params.env

secretGenerator:
  - name: pgbouncer
    files:
      - auth_file
  # The bitnami pgbouncer image requires some environment variables to work, although they are overridden by the config file
  - name: pgbouncer-bitnami
    envs:
      - secret-params.env

images:
  - name: bitnami/pgbouncer
    newTag: 1.24.0
