name: Chatbot API CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/api-ci.yml'
      - 'api/**'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/api-ci.yml'
      - 'api/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  lint:
    defaults:
      run:
        working-directory: api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.4"
          enable-cache: true
      - name: Install Dependencies
        run: uv sync --locked
      - name: Lint
        run: make lint

  test:
    defaults:
      run:
        working-directory: api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.4"
          enable-cache: true
      - name: Install Dependencies
        run: uv sync --locked
      - name: Test
        run: make test

  # We need database access to enable this job
  check-db:
    if: false
    defaults:
      run:
        working-directory: api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.4"
          enable-cache: true
      - name: Install Dependencies
        run: uv sync --locked
      - name: Check Database
        run: uv run alembic check
