name: Chatbot API CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/api-ci.yml'
      - 'api/**'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/api-ci.yml'
      - 'api/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  lint:
    defaults:
      run:
        working-directory: api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pipenv"
      - name: Install pipenv
        run: pip install pipenv
      - name: Install Dependencies
        run: pipenv sync -d
      - name: Lint
        run: make lint

  test:
    defaults:
      run:
        working-directory: api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pipenv"
      - name: Install pipenv
        run: pip install pipenv
      - name: Install Dependencies
        run: pipenv sync -d
      - name: Test
        run: make test
