name: Chatbot API check dependency hash

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/api-deps.yml'
      - 'api/Pipfile'
      - 'api/Pipfile.lock'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/api-deps.yml'
      - 'api/Pipfile'
      - 'api/Pipfile.lock'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  check-deps-hash:
    defaults:
      run:
        working-directory: api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          # cache: "pipenv"
      - name: Install pipenv
        run: pip install pipenv
      - name: Check Dependencies Hash
        run: pipenv verify
