name: Chatbot API check dependency lock

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/api-deps.yml'
      - 'api/pyproject.toml'
      - 'api/uv.lock'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/api-deps.yml'
      - 'api/pyproject.toml'
      - 'api/uv.lock'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  check-deps-lock:
    defaults:
      run:
        working-directory: api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.7.4"
          enable-cache: true
      - name: Check Dependencies Hash
        run: uv lock --check
