name: Chatbot Web CI
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/web-ci.yml'
      - 'web/**'
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/web-ci.yml'
      - 'web/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  lint:
    defaults:
        run:
          working-directory: web
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Activate Corepack
      run: corepack enable
    - name: Install modules
      run: yarn install
    - name: lint
      run: make lint
  test:
    defaults:
        run:
          working-directory: web
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Activate Corepack
      run: corepack enable
    - name: Install modules
      run: yarn install
    - name: test
      run: make test
  build:
    defaults:
        run:
          working-directory: web
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Activate Corepack
      run: corepack enable
    - name: Install modules
      run: yarn install
    - name: Build project
      run: yarn build
