apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: redis
      app.kubernetes.io/version: 7.2.0-v8
      app.kubernetes.io/managed-by: kubectl
    includeSelectors: false

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: redis/redis-stack
    newTag: 7.2.0-v8
