
# Default target executed when no arguments are given to make.
all: help

lint:
	yarn lint

format:
	yarn format

test:
	yarn test --run

build:
	yarn build

######################
# HELP
######################

help:
	@echo '----'
	@echo 'lint                         - run linters'
	@echo 'format                       - run code formatters'
	@echo 'test                         - run unit tests'
	@echo 'build                        - build the project'
